/**
 * Comprehensive In-Memory Demo Data Store
 * Provides rich, realistic hostel datasets for instant evaluation and preview
 * when running without an external MongoDB Atlas connection.
 */

const blocks = [
  {
    _id: '65fa10000000000000000010',
    name: 'Aryabhata Hall of Residence',
    blockNumber: 'A',
    gender: 'Boys',
    totalRooms: 10,
    description: 'Premier residential block for undergraduate engineers featuring high-speed optical WiFi and study rooms.',
  },
  {
    _id: '65fa10000000000000000011',
    name: 'Bhaskara Hall of Residence',
    blockNumber: 'B',
    gender: 'Boys',
    totalRooms: 8,
    description: 'Spacious block equipped with recreational table tennis room, gym corner, and open courtyard.',
  },
  {
    _id: '65fa10000000000000000012',
    name: 'Gargi Hall of Residence',
    blockNumber: 'C',
    gender: 'Girls',
    totalRooms: 8,
    description: 'Modern women resident facility with biometric security, solar heating, and indoor reading lounges.',
  },
];

const students = [
  {
    _id: 'stu-001',
    name: 'Aarav Sharma',
    email: 'student@hostel.com',
    studentId: 'STU-2026-001',
    phone: '9871100001',
    role: 'student',
    createdAt: new Date('2026-01-15'),
  },
  {
    _id: 'stu-002',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@hostel.edu',
    studentId: 'STU-2026-002',
    phone: '9871100002',
    role: 'student',
    createdAt: new Date('2026-01-16'),
  },
  {
    _id: 'stu-003',
    name: 'Aditya Singh',
    email: 'aditya.singh@hostel.edu',
    studentId: 'STU-2026-003',
    phone: '9871100003',
    role: 'student',
    createdAt: new Date('2026-01-17'),
  },
  {
    _id: 'stu-004',
    name: 'Kunal Patel',
    email: 'kunal.patel@hostel.edu',
    studentId: 'STU-2026-004',
    phone: '9871100004',
    role: 'student',
    createdAt: new Date('2026-01-18'),
  },
  {
    _id: 'stu-005',
    name: 'Devansh Verma',
    email: 'devansh.verma@hostel.edu',
    studentId: 'STU-2026-005',
    phone: '9871100005',
    role: 'student',
    createdAt: new Date('2026-01-19'),
  },
  {
    _id: 'stu-006',
    name: 'Ananya Roy',
    email: 'ananya.roy@hostel.edu',
    studentId: 'STU-2026-006',
    phone: '9871100006',
    role: 'student',
    createdAt: new Date('2026-01-20'),
  },
  {
    _id: 'stu-007',
    name: 'Priya Iyer',
    email: 'priya.iyer@hostel.edu',
    studentId: 'STU-2026-007',
    phone: '9871100007',
    role: 'student',
    createdAt: new Date('2026-01-21'),
  },
  {
    _id: 'stu-008',
    name: 'Sneha Kulkarni',
    email: 'sneha.kulkarni@hostel.edu',
    studentId: 'STU-2026-008',
    phone: '9871100008',
    role: 'student',
    createdAt: new Date('2026-01-22'),
  },
];

const admin = {
  _id: 'admin-001',
  name: 'Chief Warden Dr. Rajesh Verma',
  email: 'admin@hostel.com',
  studentId: 'ADMIN-001',
  phone: '9876543210',
  role: 'admin',
  createdAt: new Date('2026-01-01'),
};

const rooms = [
  // Block A
  {
    _id: 'room-a-101',
    roomNumber: 'A-101',
    block: blocks[0],
    roomType: 'Single',
    capacity: 1,
    occupiedBeds: 1,
    status: 'Full',
    students: [students[2]],
  },
  {
    _id: 'room-a-102',
    roomNumber: 'A-102',
    block: blocks[0],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 2,
    status: 'Full',
    students: [students[0], students[1]],
  },
  {
    _id: 'room-a-103',
    roomNumber: 'A-103',
    block: blocks[0],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-a-104',
    roomNumber: 'A-104',
    block: blocks[0],
    roomType: 'Triple',
    capacity: 3,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-a-105',
    roomNumber: 'A-105',
    block: blocks[0],
    roomType: 'Four Sharing',
    capacity: 4,
    occupiedBeds: 1,
    status: 'Partially Occupied',
    students: [students[3]],
  },
  {
    _id: 'room-a-201',
    roomNumber: 'A-201',
    block: blocks[0],
    roomType: 'Single',
    capacity: 1,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-a-202',
    roomNumber: 'A-202',
    block: blocks[0],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-a-203',
    roomNumber: 'A-203',
    block: blocks[0],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-a-204',
    roomNumber: 'A-204',
    block: blocks[0],
    roomType: 'Four Sharing',
    capacity: 4,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-a-205',
    roomNumber: 'A-205',
    block: blocks[0],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 0,
    status: 'Maintenance',
    students: [],
  },

  // Block B
  {
    _id: 'room-b-101',
    roomNumber: 'B-101',
    block: blocks[1],
    roomType: 'Single',
    capacity: 1,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-b-102',
    roomNumber: 'B-102',
    block: blocks[1],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-b-103',
    roomNumber: 'B-103',
    block: blocks[1],
    roomType: 'Triple',
    capacity: 3,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-b-104',
    roomNumber: 'B-104',
    block: blocks[1],
    roomType: 'Four Sharing',
    capacity: 4,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-b-201',
    roomNumber: 'B-201',
    block: blocks[1],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-b-202',
    roomNumber: 'B-202',
    block: blocks[1],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-b-203',
    roomNumber: 'B-203',
    block: blocks[1],
    roomType: 'Triple',
    capacity: 3,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-b-204',
    roomNumber: 'B-204',
    block: blocks[1],
    roomType: 'Four Sharing',
    capacity: 4,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },

  // Block C (Girls)
  {
    _id: 'room-c-101',
    roomNumber: 'C-101',
    block: blocks[2],
    roomType: 'Single',
    capacity: 1,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-c-102',
    roomNumber: 'C-102',
    block: blocks[2],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 2,
    status: 'Full',
    students: [students[5], students[6]],
  },
  {
    _id: 'room-c-103',
    roomNumber: 'C-103',
    block: blocks[2],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-c-104',
    roomNumber: 'C-104',
    block: blocks[2],
    roomType: 'Triple',
    capacity: 3,
    occupiedBeds: 1,
    status: 'Partially Occupied',
    students: [students[7]],
  },
  {
    _id: 'room-c-105',
    roomNumber: 'C-105',
    block: blocks[2],
    roomType: 'Four Sharing',
    capacity: 4,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-c-201',
    roomNumber: 'C-201',
    block: blocks[2],
    roomType: 'Single',
    capacity: 1,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-c-202',
    roomNumber: 'C-202',
    block: blocks[2],
    roomType: 'Double',
    capacity: 2,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
  {
    _id: 'room-c-203',
    roomNumber: 'C-203',
    block: blocks[2],
    roomType: 'Four Sharing',
    capacity: 4,
    occupiedBeds: 0,
    status: 'Available',
    students: [],
  },
];

// Attach room references to students
students[0].room = rooms[1]; // Aarav in A-102
students[1].room = rooms[1]; // Rohan in A-102
students[2].room = rooms[0]; // Aditya in A-101
students[3].room = rooms[4]; // Kunal in A-105
students[4].room = null;      // Devansh unallotted
students[5].room = rooms[19]; // Ananya in C-102
students[6].room = rooms[19]; // Priya in C-102
students[7].room = rooms[21]; // Sneha in C-104

const roomRequests = [
  {
    _id: 'req-001',
    student: students[4], // Devansh
    preferredBlock: blocks[0],
    preferredRoomType: 'Double',
    reason: 'Department of Computer Science proximity required for lab projects.',
    status: 'Pending',
    createdAt: new Date('2026-09-15'),
  },
  {
    _id: 'req-002',
    student: students[0], // Aarav
    preferredBlock: blocks[0],
    preferredRoomType: 'Double',
    reason: 'Allotment request for standard semester housing.',
    status: 'Approved',
    adminRemarks: 'Allotted to Room A-102',
    reviewedAt: new Date('2026-09-10'),
    createdAt: new Date('2026-09-08'),
  },
];

const roomChangeRequests = [
  {
    _id: 'cr-001',
    student: students[3], // Kunal in A-105
    currentRoom: rooms[4],
    requestedRoom: rooms[11], // B-102
    reason: 'Joining project group with students residing on Block B first floor.',
    status: 'Pending',
    createdAt: new Date('2026-09-16'),
  },
];

const maintenanceRequests = [
  {
    _id: 'maint-001',
    student: students[0], // Aarav in A-102
    room: rooms[1],
    category: 'Electrical',
    description: 'Ceiling fan regulator is stuck at speed 2 and vibrating noisily.',
    priority: 'Medium',
    status: 'In Progress',
    adminRemarks: 'Electrician assigned work order #104.',
    createdAt: new Date('2026-09-14'),
  },
  {
    _id: 'maint-002',
    student: students[5], // Ananya in C-102
    room: rooms[19],
    category: 'Plumbing',
    description: 'Washbasin drain pipe is leaking water under the counter.',
    priority: 'High',
    status: 'Pending',
    adminRemarks: '',
    createdAt: new Date('2026-09-17'),
  },
  {
    _id: 'maint-003',
    student: students[2], // Aditya in A-101
    room: rooms[0],
    category: 'Internet / WiFi',
    description: 'WiFi access point in corridor dropping connectivity intermittently.',
    priority: 'Low',
    status: 'Resolved',
    adminRemarks: 'Replaced router antenna, signal restored at 100Mbps.',
    resolvedAt: new Date('2026-09-12'),
    createdAt: new Date('2026-09-11'),
  },
];

const messMenu = {
  _id: 'menu-001',
  isActive: true,
  weekStartDate: new Date('2026-09-15'),
  monday: {
    breakfast: 'Idli, Medu Vada, Coconut Chutney, Sambar, Tea / Coffee',
    lunch: 'Steamed Basmati Rice, Yellow Dal Tadka, Aloo Gobhi, Phulka Roti, Salad',
    snacks: 'Veg Cutlet, Green Mint Chutney, Masala Chai',
    dinner: 'Paneer Butter Masala, Butter Naan, Jeera Rice, Dal Makhani, Gulab Jamun',
    specialItem: 'Paneer Butter Masala & Gulab Jamun',
    dietaryType: 'veg',
  },
  tuesday: {
    breakfast: 'Poha with Peanuts, Sev, Boiled Eggs / Banana, Tea / Coffee',
    lunch: 'Rajma Masala, Steamed Rice, Mix Veg Sabzi, Tawa Roti, Curd',
    snacks: 'Samosa, Tamarind Chutney, Ginger Tea',
    dinner: 'Egg Curry / Malai Kofta, Lachha Paratha, Veg Pulao, Moong Dal Halwa',
    specialItem: 'Egg Curry / Malai Kofta',
    dietaryType: 'special',
  },
  wednesday: {
    breakfast: 'Masala Dosa, Sambhar, Tomato Chutney, Filter Coffee',
    lunch: 'Kadhi Pakora, Steamed Rice, Bhindi Masala, Chapati, Boondi Raita',
    snacks: 'Bhel Puri, Sweet Corn, Hot Lemon Tea',
    dinner: 'Chicken Biryani / Paneer Dum Biryani, Mirchi Ka Salan, Raita',
    specialItem: 'Chicken / Paneer Dum Biryani',
    dietaryType: 'special',
  },
  thursday: {
    breakfast: 'Aloo Paratha with Butter, Curd, Mixed Pickle, Tea',
    lunch: 'Chole Masala, Bhature, Steamed Rice, Green Salad, Pickled Onions',
    snacks: 'Onion Pakoda, Masala Chai, Biscuits',
    dinner: 'Dal Tadka, Mix Veg Korma, Tawa Roti, Steamed Rice, Rasgulla',
    specialItem: 'Chole Bhature Lunch Fest',
    dietaryType: 'veg',
  },
  friday: {
    breakfast: 'Upma, Sambar, Coconut Chutney, Boiled Sprouts, Coffee',
    lunch: 'Dal Makhani, Jeera Rice, Baingan Bharta, Butter Roti, Papad',
    snacks: 'Pav Bhaji, Chopped Onions, Lemon, Cutting Chai',
    dinner: 'Kadhai Paneer, Roomali Roti, Veg Pulao, Yellow Dal, Fruit Custard',
    specialItem: 'Fruit Custard & Pav Bhaji',
    dietaryType: 'veg',
  },
  saturday: {
    breakfast: 'Poori Bhaji, Halwa, Pickle, Milk / Tea',
    lunch: 'Sambhar Rice, Curd Rice, Potato Poriyal, Appalam, Pickle',
    snacks: 'Dhokla, Fried Green Chillies, Sweet Chutney, Tea',
    dinner: 'Tandoori Roti, Shahi Paneer, Dal Fry, Jeera Rice, Ice Cream',
    specialItem: 'Shahi Paneer & Vanilla Ice Cream',
    dietaryType: 'special',
  },
  sunday: {
    breakfast: 'Uttapam with Sambar, Coconut Chutney, Filter Coffee',
    lunch: 'Special Sunday Feast: Paneer Tikka Masala / Butter Chicken, Jeera Rice, Naan, Gulab Jamun',
    snacks: 'French Fries, Filter Coffee, Cookies',
    dinner: 'Light Khichdi, Gujarati Kadhi, Aloo Chokha, Roasted Papad',
    specialItem: 'Sunday Grand Feast',
    dietaryType: 'special',
  },
};

const mealFeedback = [
  {
    _id: 'fb-001',
    student: students[0],
    mealType: 'Dinner',
    rating: 5,
    comment: 'The Biryani and salan combination was top tier tonight! Very flavorful and served hot.',
    createdAt: new Date('2026-09-17T20:30:00'),
  },
  {
    _id: 'fb-002',
    student: students[5],
    mealType: 'Lunch',
    rating: 4,
    comment: 'Chole were nicely cooked, but bhature were slightly oily. Overall good meal.',
    createdAt: new Date('2026-09-17T13:45:00'),
  },
  {
    _id: 'fb-003',
    student: students[3],
    mealType: 'Breakfast',
    rating: 4,
    comment: 'Crisp masala dosa and fresh coconut chutney. Keep it up!',
    createdAt: new Date('2026-09-18T08:30:00'),
  },
];

const messBills = [
  {
    _id: 'bill-001',
    student: students[0], // Aarav
    month: 'September',
    year: 2026,
    baseMessFee: 4200,
    dailyMealRate: 140,
    attendedDays: 28,
    extraCharges: 150,
    rebateAmount: 0,
    totalAmount: 4350,
    status: 'Paid',
    paidAt: new Date('2026-09-10'),
    paymentReference: 'UPI/20260910/987110001',
    generatedAt: new Date('2026-09-01'),
  },
  {
    _id: 'bill-002',
    student: students[1], // Rohan
    month: 'September',
    year: 2026,
    baseMessFee: 4200,
    dailyMealRate: 140,
    attendedDays: 25,
    extraCharges: 0,
    rebateAmount: 420,
    totalAmount: 3780,
    status: 'Unpaid',
    dueDate: new Date('2026-09-25'),
    generatedAt: new Date('2026-09-01'),
  },
];

module.exports = {
  blocks,
  students,
  admin,
  rooms,
  roomRequests,
  roomChangeRequests,
  maintenanceRequests,
  messMenu,
  mealFeedback,
  messBills,
};
